// flow-typed signature: 5b31f832b3656d2ff7789647a7294614
// flow-typed version: <<STUB>>/fugazi_v^0.5.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fugazi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fugazi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fugazi/index' {
  declare module.exports: $Exports<'fugazi'>;
}
declare module 'fugazi/index.js' {
  declare module.exports: $Exports<'fugazi'>;
}
