// flow-typed signature: 488a4e60cc8e8d9d09192a24e9d809c3
// flow-typed version: <<STUB>>/graphql-server-lambda_v^0.7.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-server-lambda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-server-lambda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-server-lambda/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-server-lambda/dist/lambdaApollo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-server-lambda/dist/index.js' {
  declare module.exports: $Exports<'graphql-server-lambda/dist/index'>;
}
declare module 'graphql-server-lambda/dist/lambdaApollo.js' {
  declare module.exports: $Exports<'graphql-server-lambda/dist/lambdaApollo'>;
}
