// flow-typed signature: 2779019a92798ce083d5204d1dd6e4ba
// flow-typed version: <<STUB>>/lambda-wrapper_v^0.1.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lambda-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lambda-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lambda-wrapper/lambdaWrapper-test' {
  declare module.exports: any;
}

declare module 'lambda-wrapper/test/test-wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lambda-wrapper/index' {
  declare module.exports: $Exports<'lambda-wrapper'>;
}
declare module 'lambda-wrapper/index.js' {
  declare module.exports: $Exports<'lambda-wrapper'>;
}
declare module 'lambda-wrapper/lambdaWrapper-test.js' {
  declare module.exports: $Exports<'lambda-wrapper/lambdaWrapper-test'>;
}
declare module 'lambda-wrapper/test/test-wrapper.js' {
  declare module.exports: $Exports<'lambda-wrapper/test/test-wrapper'>;
}
