// flow-typed signature: 05726fdc62ad991f4bdeb00ff02513f6
// flow-typed version: <<STUB>>/now_v^4.10.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'now'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'now' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'now/build/bin/now-alias' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-billing-add' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-billing' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-certs' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-deploy' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-dns' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-domains' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-list' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-open' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-remove' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-secrets' {
  declare module.exports: any;
}

declare module 'now/build/bin/now-upgrade' {
  declare module.exports: any;
}

declare module 'now/build/bin/now' {
  declare module.exports: any;
}

declare module 'now/build/lib/agent' {
  declare module.exports: any;
}

declare module 'now/build/lib/alias' {
  declare module.exports: any;
}

declare module 'now/build/lib/build-logger' {
  declare module.exports: any;
}

declare module 'now/build/lib/certs' {
  declare module.exports: any;
}

declare module 'now/build/lib/cfg' {
  declare module.exports: any;
}

declare module 'now/build/lib/copy' {
  declare module.exports: any;
}

declare module 'now/build/lib/credit-cards' {
  declare module.exports: any;
}

declare module 'now/build/lib/dns' {
  declare module.exports: any;
}

declare module 'now/build/lib/domain-records' {
  declare module.exports: any;
}

declare module 'now/build/lib/domains' {
  declare module.exports: any;
}

declare module 'now/build/lib/error' {
  declare module.exports: any;
}

declare module 'now/build/lib/errors' {
  declare module.exports: any;
}

declare module 'now/build/lib/get-files' {
  declare module.exports: any;
}

declare module 'now/build/lib/git' {
  declare module.exports: any;
}

declare module 'now/build/lib/hash' {
  declare module.exports: any;
}

declare module 'now/build/lib/ignored' {
  declare module.exports: any;
}

declare module 'now/build/lib/indent' {
  declare module.exports: any;
}

declare module 'now/build/lib/index' {
  declare module.exports: any;
}

declare module 'now/build/lib/is-zeit-world' {
  declare module.exports: any;
}

declare module 'now/build/lib/login' {
  declare module.exports: any;
}

declare module 'now/build/lib/logs' {
  declare module.exports: any;
}

declare module 'now/build/lib/pkg' {
  declare module.exports: any;
}

declare module 'now/build/lib/plans' {
  declare module.exports: any;
}

declare module 'now/build/lib/re-alias' {
  declare module.exports: any;
}

declare module 'now/build/lib/read-metadata' {
  declare module.exports: any;
}

declare module 'now/build/lib/secrets' {
  declare module.exports: any;
}

declare module 'now/build/lib/strlen' {
  declare module.exports: any;
}

declare module 'now/build/lib/test' {
  declare module.exports: any;
}

declare module 'now/build/lib/to-host' {
  declare module.exports: any;
}

declare module 'now/build/lib/ua' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/billing/geocode' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/check-path' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/exit' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/input/list' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/input/prompt-bool' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/input/text' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/output/cmd' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/output/code' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/output/error' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/output/info' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/output/logo' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/output/param' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/output/stamp' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/output/success' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/output/uid' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/output/wait' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/prompt-options' {
  declare module.exports: any;
}

declare module 'now/build/lib/utils/to-human-path' {
  declare module.exports: any;
}

// Filename aliases
declare module 'now/build/bin/now-alias.js' {
  declare module.exports: $Exports<'now/build/bin/now-alias'>;
}
declare module 'now/build/bin/now-billing-add.js' {
  declare module.exports: $Exports<'now/build/bin/now-billing-add'>;
}
declare module 'now/build/bin/now-billing.js' {
  declare module.exports: $Exports<'now/build/bin/now-billing'>;
}
declare module 'now/build/bin/now-certs.js' {
  declare module.exports: $Exports<'now/build/bin/now-certs'>;
}
declare module 'now/build/bin/now-deploy.js' {
  declare module.exports: $Exports<'now/build/bin/now-deploy'>;
}
declare module 'now/build/bin/now-dns.js' {
  declare module.exports: $Exports<'now/build/bin/now-dns'>;
}
declare module 'now/build/bin/now-domains.js' {
  declare module.exports: $Exports<'now/build/bin/now-domains'>;
}
declare module 'now/build/bin/now-list.js' {
  declare module.exports: $Exports<'now/build/bin/now-list'>;
}
declare module 'now/build/bin/now-open.js' {
  declare module.exports: $Exports<'now/build/bin/now-open'>;
}
declare module 'now/build/bin/now-remove.js' {
  declare module.exports: $Exports<'now/build/bin/now-remove'>;
}
declare module 'now/build/bin/now-secrets.js' {
  declare module.exports: $Exports<'now/build/bin/now-secrets'>;
}
declare module 'now/build/bin/now-upgrade.js' {
  declare module.exports: $Exports<'now/build/bin/now-upgrade'>;
}
declare module 'now/build/bin/now.js' {
  declare module.exports: $Exports<'now/build/bin/now'>;
}
declare module 'now/build/lib/agent.js' {
  declare module.exports: $Exports<'now/build/lib/agent'>;
}
declare module 'now/build/lib/alias.js' {
  declare module.exports: $Exports<'now/build/lib/alias'>;
}
declare module 'now/build/lib/build-logger.js' {
  declare module.exports: $Exports<'now/build/lib/build-logger'>;
}
declare module 'now/build/lib/certs.js' {
  declare module.exports: $Exports<'now/build/lib/certs'>;
}
declare module 'now/build/lib/cfg.js' {
  declare module.exports: $Exports<'now/build/lib/cfg'>;
}
declare module 'now/build/lib/copy.js' {
  declare module.exports: $Exports<'now/build/lib/copy'>;
}
declare module 'now/build/lib/credit-cards.js' {
  declare module.exports: $Exports<'now/build/lib/credit-cards'>;
}
declare module 'now/build/lib/dns.js' {
  declare module.exports: $Exports<'now/build/lib/dns'>;
}
declare module 'now/build/lib/domain-records.js' {
  declare module.exports: $Exports<'now/build/lib/domain-records'>;
}
declare module 'now/build/lib/domains.js' {
  declare module.exports: $Exports<'now/build/lib/domains'>;
}
declare module 'now/build/lib/error.js' {
  declare module.exports: $Exports<'now/build/lib/error'>;
}
declare module 'now/build/lib/errors.js' {
  declare module.exports: $Exports<'now/build/lib/errors'>;
}
declare module 'now/build/lib/get-files.js' {
  declare module.exports: $Exports<'now/build/lib/get-files'>;
}
declare module 'now/build/lib/git.js' {
  declare module.exports: $Exports<'now/build/lib/git'>;
}
declare module 'now/build/lib/hash.js' {
  declare module.exports: $Exports<'now/build/lib/hash'>;
}
declare module 'now/build/lib/ignored.js' {
  declare module.exports: $Exports<'now/build/lib/ignored'>;
}
declare module 'now/build/lib/indent.js' {
  declare module.exports: $Exports<'now/build/lib/indent'>;
}
declare module 'now/build/lib/index.js' {
  declare module.exports: $Exports<'now/build/lib/index'>;
}
declare module 'now/build/lib/is-zeit-world.js' {
  declare module.exports: $Exports<'now/build/lib/is-zeit-world'>;
}
declare module 'now/build/lib/login.js' {
  declare module.exports: $Exports<'now/build/lib/login'>;
}
declare module 'now/build/lib/logs.js' {
  declare module.exports: $Exports<'now/build/lib/logs'>;
}
declare module 'now/build/lib/pkg.js' {
  declare module.exports: $Exports<'now/build/lib/pkg'>;
}
declare module 'now/build/lib/plans.js' {
  declare module.exports: $Exports<'now/build/lib/plans'>;
}
declare module 'now/build/lib/re-alias.js' {
  declare module.exports: $Exports<'now/build/lib/re-alias'>;
}
declare module 'now/build/lib/read-metadata.js' {
  declare module.exports: $Exports<'now/build/lib/read-metadata'>;
}
declare module 'now/build/lib/secrets.js' {
  declare module.exports: $Exports<'now/build/lib/secrets'>;
}
declare module 'now/build/lib/strlen.js' {
  declare module.exports: $Exports<'now/build/lib/strlen'>;
}
declare module 'now/build/lib/test.js' {
  declare module.exports: $Exports<'now/build/lib/test'>;
}
declare module 'now/build/lib/to-host.js' {
  declare module.exports: $Exports<'now/build/lib/to-host'>;
}
declare module 'now/build/lib/ua.js' {
  declare module.exports: $Exports<'now/build/lib/ua'>;
}
declare module 'now/build/lib/utils/billing/geocode.js' {
  declare module.exports: $Exports<'now/build/lib/utils/billing/geocode'>;
}
declare module 'now/build/lib/utils/check-path.js' {
  declare module.exports: $Exports<'now/build/lib/utils/check-path'>;
}
declare module 'now/build/lib/utils/exit.js' {
  declare module.exports: $Exports<'now/build/lib/utils/exit'>;
}
declare module 'now/build/lib/utils/input/list.js' {
  declare module.exports: $Exports<'now/build/lib/utils/input/list'>;
}
declare module 'now/build/lib/utils/input/prompt-bool.js' {
  declare module.exports: $Exports<'now/build/lib/utils/input/prompt-bool'>;
}
declare module 'now/build/lib/utils/input/text.js' {
  declare module.exports: $Exports<'now/build/lib/utils/input/text'>;
}
declare module 'now/build/lib/utils/output/cmd.js' {
  declare module.exports: $Exports<'now/build/lib/utils/output/cmd'>;
}
declare module 'now/build/lib/utils/output/code.js' {
  declare module.exports: $Exports<'now/build/lib/utils/output/code'>;
}
declare module 'now/build/lib/utils/output/error.js' {
  declare module.exports: $Exports<'now/build/lib/utils/output/error'>;
}
declare module 'now/build/lib/utils/output/info.js' {
  declare module.exports: $Exports<'now/build/lib/utils/output/info'>;
}
declare module 'now/build/lib/utils/output/logo.js' {
  declare module.exports: $Exports<'now/build/lib/utils/output/logo'>;
}
declare module 'now/build/lib/utils/output/param.js' {
  declare module.exports: $Exports<'now/build/lib/utils/output/param'>;
}
declare module 'now/build/lib/utils/output/stamp.js' {
  declare module.exports: $Exports<'now/build/lib/utils/output/stamp'>;
}
declare module 'now/build/lib/utils/output/success.js' {
  declare module.exports: $Exports<'now/build/lib/utils/output/success'>;
}
declare module 'now/build/lib/utils/output/uid.js' {
  declare module.exports: $Exports<'now/build/lib/utils/output/uid'>;
}
declare module 'now/build/lib/utils/output/wait.js' {
  declare module.exports: $Exports<'now/build/lib/utils/output/wait'>;
}
declare module 'now/build/lib/utils/prompt-options.js' {
  declare module.exports: $Exports<'now/build/lib/utils/prompt-options'>;
}
declare module 'now/build/lib/utils/to-human-path.js' {
  declare module.exports: $Exports<'now/build/lib/utils/to-human-path'>;
}
