// flow-typed signature: 7fdfd9873e6f68e1f11896d49106ca84
// flow-typed version: <<STUB>>/react-helmet_v^5.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module "react-helmet" {
  declare type Props = {
    htmlAttributes?: Object,
    title?: string,
    defaultTitle?: string,
    titleTemplate?: string,
    base?: Object,
    meta?: Array<Object>,
    link?: Array<Object>,
    script?: Array<Object>,
    noscript?: Array<Object>,
    style?: Array<Object>,
    onChangeClientState?: (
      newState: Object,
      addedTags: Object,
      removeTags: Object,
    ) => void | mixed,
  };
  declare interface HeadAttribute {
    toString(): string,
    toComponent(): React$Element<*>,
  }
  declare interface Head {
    htmlAttributes: HeadAttribute,
    title: HeadAttribute,
    base: HeadAttribute,
    meta: HeadAttribute,
    link: HeadAttribute,
    script: HeadAttribute,
    style: HeadAttribute,
  }

  declare class Helmet extends React$Component {
    static renderStatic(): Head,
    props: Props,
  }
  declare var exports: typeof Helmet;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "react-helmet/es/Helmet" {
  declare module.exports: any;
}

declare module "react-helmet/es/HelmetConstants" {
  declare module.exports: any;
}

declare module "react-helmet/es/HelmetUtils" {
  declare module.exports: any;
}

declare module "react-helmet/lib/Helmet" {
  declare module.exports: any;
}

declare module "react-helmet/lib/HelmetConstants" {
  declare module.exports: any;
}

declare module "react-helmet/lib/HelmetUtils" {
  declare module.exports: any;
}

declare module "react-helmet/test/HelmetDeclarativeTest" {
  declare module.exports: any;
}

declare module "react-helmet/test/HelmetTest" {
  declare module.exports: any;
}

declare module "react-helmet/test/test" {
  declare module.exports: any;
}

// Filename aliases
declare module "react-helmet/es/Helmet.js" {
  declare module.exports: $Exports<"react-helmet/es/Helmet">;
}
declare module "react-helmet/es/HelmetConstants.js" {
  declare module.exports: $Exports<"react-helmet/es/HelmetConstants">;
}
declare module "react-helmet/es/HelmetUtils.js" {
  declare module.exports: $Exports<"react-helmet/es/HelmetUtils">;
}
declare module "react-helmet/lib/Helmet.js" {
  declare module.exports: $Exports<"react-helmet/lib/Helmet">;
}
declare module "react-helmet/lib/HelmetConstants.js" {
  declare module.exports: $Exports<"react-helmet/lib/HelmetConstants">;
}
declare module "react-helmet/lib/HelmetUtils.js" {
  declare module.exports: $Exports<"react-helmet/lib/HelmetUtils">;
}
declare module "react-helmet/test/HelmetDeclarativeTest.js" {
  declare module.exports: $Exports<"react-helmet/test/HelmetDeclarativeTest">;
}
declare module "react-helmet/test/HelmetTest.js" {
  declare module.exports: $Exports<"react-helmet/test/HelmetTest">;
}
declare module "react-helmet/test/test.js" {
  declare module.exports: $Exports<"react-helmet/test/test">;
}
