// flow-typed signature: b4767a268db6ef8226050deba635eb64
// flow-typed version: <<STUB>>/rnpm-plugin-windows_v^0.2.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rnpm-plugin-windows'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rnpm-plugin-windows' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rnpm-plugin-windows/src/common' {
  declare module.exports: any;
}

declare module 'rnpm-plugin-windows/src/windows' {
  declare module.exports: any;
}

declare module 'rnpm-plugin-windows/src/wpf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rnpm-plugin-windows/index' {
  declare module.exports: $Exports<'rnpm-plugin-windows'>;
}
declare module 'rnpm-plugin-windows/index.js' {
  declare module.exports: $Exports<'rnpm-plugin-windows'>;
}
declare module 'rnpm-plugin-windows/src/common.js' {
  declare module.exports: $Exports<'rnpm-plugin-windows/src/common'>;
}
declare module 'rnpm-plugin-windows/src/windows.js' {
  declare module.exports: $Exports<'rnpm-plugin-windows/src/windows'>;
}
declare module 'rnpm-plugin-windows/src/wpf.js' {
  declare module.exports: $Exports<'rnpm-plugin-windows/src/wpf'>;
}
