// flow-typed signature: b59b95561d2b5629d39852d6c0c4c69d
// flow-typed version: <<STUB>>/serverless_v^1.12.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless/lib/classes/CLI' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/CLI.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Config' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Config.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Error' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Error.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/PluginManager' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/PluginManager.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Service' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Service.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Utils' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Utils.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Variables' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/Variables.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/YamlParser' {
  declare module.exports: any;
}

declare module 'serverless/lib/classes/YamlParser.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/lib/artifacts' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/lib/artifacts.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/lib/cleanupTempDir' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/common/lib/cleanupTempDir.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/createStack' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/createStack.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/extendedValidate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deployFunction/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deployFunction/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deployList/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/deployList/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/display' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/display.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/getApiKeyValues' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/getApiKeyValues.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/getStackInfo' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/getStackInfo.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/info/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invoke/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invoke/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithError' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithSuccess' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invokeLocal/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/invokeLocal/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/monitorStack' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/monitorStack.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/naming' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/naming.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/setBucketName' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/setBucketName.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/updateStack' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/updateStack.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/validate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/validate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/validateS3BucketName' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/lib/validateS3BucketName.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/logs/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/logs/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/metrics/awsMetrics' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/metrics/awsMetrics.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/iot/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/iot/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/s3/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/s3/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/schedule/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/schedule/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/sns/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/sns/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/stream/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/events/stream/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/functions/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/compile/functions/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/generateCoreTemplate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/generateCoreTemplate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/mergeIamTemplates' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/mergeIamTemplates.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/saveServiceState' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/package/lib/saveServiceState.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/provider/awsProvider' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/provider/awsProvider.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/lib/bucket' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/lib/bucket.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/lib/stack' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/remove/lib/stack.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/rollback/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/rollback/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/findAndGroupDeployments' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/findAndGroupDeployments.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/findReferences' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/findReferences.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/config/config' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/config/config.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/create' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/create.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/aws-nodejs/handler' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/azure-nodejs/handler' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/openwhisk-nodejs/handler' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/create/templates/plugin/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/deploy/deploy' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/deploy/deploy.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/info/info' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/info/info.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/install/install' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/install/install.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/invoke/invoke' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/invoke/invoke.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/logs/logs' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/logs/logs.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/metrics/metrics' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/metrics/metrics.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/lib/packageService' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/lib/packageService.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/lib/zipService' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/lib/zipService.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/package' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/package/package.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/remove/remove' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/remove/remove.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/rollback/index' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/rollback/index.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/slstats/slstats' {
  declare module.exports: any;
}

declare module 'serverless/lib/plugins/slstats/slstats.test' {
  declare module.exports: any;
}

declare module 'serverless/lib/Serverless' {
  declare module.exports: any;
}

declare module 'serverless/lib/Serverless.test' {
  declare module.exports: any;
}

declare module 'serverless/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'serverless/scripts/preuninstall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless/lib/classes/CLI.js' {
  declare module.exports: $Exports<'serverless/lib/classes/CLI'>;
}
declare module 'serverless/lib/classes/CLI.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/CLI.test'>;
}
declare module 'serverless/lib/classes/Config.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Config'>;
}
declare module 'serverless/lib/classes/Config.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Config.test'>;
}
declare module 'serverless/lib/classes/Error.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Error'>;
}
declare module 'serverless/lib/classes/Error.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Error.test'>;
}
declare module 'serverless/lib/classes/PluginManager.js' {
  declare module.exports: $Exports<'serverless/lib/classes/PluginManager'>;
}
declare module 'serverless/lib/classes/PluginManager.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/PluginManager.test'>;
}
declare module 'serverless/lib/classes/Service.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Service'>;
}
declare module 'serverless/lib/classes/Service.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Service.test'>;
}
declare module 'serverless/lib/classes/Utils.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Utils'>;
}
declare module 'serverless/lib/classes/Utils.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Utils.test'>;
}
declare module 'serverless/lib/classes/Variables.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Variables'>;
}
declare module 'serverless/lib/classes/Variables.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/Variables.test'>;
}
declare module 'serverless/lib/classes/YamlParser.js' {
  declare module.exports: $Exports<'serverless/lib/classes/YamlParser'>;
}
declare module 'serverless/lib/classes/YamlParser.test.js' {
  declare module.exports: $Exports<'serverless/lib/classes/YamlParser.test'>;
}
declare module 'serverless/lib/plugins/aws/common/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/index'>;
}
declare module 'serverless/lib/plugins/aws/common/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/index.test'>;
}
declare module 'serverless/lib/plugins/aws/common/lib/artifacts.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/lib/artifacts'>;
}
declare module 'serverless/lib/plugins/aws/common/lib/artifacts.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/lib/artifacts.test'>;
}
declare module 'serverless/lib/plugins/aws/common/lib/cleanupTempDir.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/lib/cleanupTempDir'>;
}
declare module 'serverless/lib/plugins/aws/common/lib/cleanupTempDir.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/common/lib/cleanupTempDir.test'>;
}
declare module 'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials'>;
}
declare module 'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/configCredentials/awsConfigCredentials.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/index'>;
}
declare module 'serverless/lib/plugins/aws/deploy/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/index.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/cleanupS3Bucket.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/createStack.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/createStack'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/createStack.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/createStack.test'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/extendedValidate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/extendedValidate'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts'>;
}
declare module 'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deploy/lib/uploadArtifacts.test'>;
}
declare module 'serverless/lib/plugins/aws/deployFunction/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deployFunction/index'>;
}
declare module 'serverless/lib/plugins/aws/deployFunction/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deployFunction/index.test'>;
}
declare module 'serverless/lib/plugins/aws/deployList/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deployList/index'>;
}
declare module 'serverless/lib/plugins/aws/deployList/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/deployList/index.test'>;
}
declare module 'serverless/lib/plugins/aws/info/display.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/display'>;
}
declare module 'serverless/lib/plugins/aws/info/display.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/display.test'>;
}
declare module 'serverless/lib/plugins/aws/info/getApiKeyValues.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/getApiKeyValues'>;
}
declare module 'serverless/lib/plugins/aws/info/getApiKeyValues.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/getApiKeyValues.test'>;
}
declare module 'serverless/lib/plugins/aws/info/getStackInfo.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/getStackInfo'>;
}
declare module 'serverless/lib/plugins/aws/info/getStackInfo.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/getStackInfo.test'>;
}
declare module 'serverless/lib/plugins/aws/info/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/index'>;
}
declare module 'serverless/lib/plugins/aws/info/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/info/index.test'>;
}
declare module 'serverless/lib/plugins/aws/invoke/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invoke/index'>;
}
declare module 'serverless/lib/plugins/aws/invoke/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invoke/index.test'>;
}
declare module 'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithError.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithError'>;
}
declare module 'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithSuccess.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invokeLocal/fixture/handlerWithSuccess'>;
}
declare module 'serverless/lib/plugins/aws/invokeLocal/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invokeLocal/index'>;
}
declare module 'serverless/lib/plugins/aws/invokeLocal/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/invokeLocal/index.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/monitorStack.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/monitorStack'>;
}
declare module 'serverless/lib/plugins/aws/lib/monitorStack.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/monitorStack.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/naming.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/naming'>;
}
declare module 'serverless/lib/plugins/aws/lib/naming.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/naming.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/setBucketName.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/setBucketName'>;
}
declare module 'serverless/lib/plugins/aws/lib/setBucketName.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/setBucketName.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/updateStack.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/updateStack'>;
}
declare module 'serverless/lib/plugins/aws/lib/updateStack.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/updateStack.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/validate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/validate'>;
}
declare module 'serverless/lib/plugins/aws/lib/validate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/validate.test'>;
}
declare module 'serverless/lib/plugins/aws/lib/validateS3BucketName.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/validateS3BucketName'>;
}
declare module 'serverless/lib/plugins/aws/lib/validateS3BucketName.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/lib/validateS3BucketName.test'>;
}
declare module 'serverless/lib/plugins/aws/logs/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/logs/index'>;
}
declare module 'serverless/lib/plugins/aws/logs/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/logs/index.test'>;
}
declare module 'serverless/lib/plugins/aws/metrics/awsMetrics.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/metrics/awsMetrics'>;
}
declare module 'serverless/lib/plugins/aws/metrics/awsMetrics.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/metrics/awsMetrics.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/alexaSkill/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/apiKeys.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/authorizers.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/cors.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/deployment.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/authorization'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/integration'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/method/responses'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/permissions.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/resources.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/restApi.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/apiGateway/lib/validate.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/cloudWatchEvent/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/cloudWatchLog/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/iot/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/iot/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/iot/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/iot/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/s3/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/s3/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/s3/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/s3/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/schedule/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/schedule/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/schedule/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/schedule/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/sns/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/sns/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/sns/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/sns/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/stream/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/stream/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/events/stream/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/events/stream/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/functions/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/functions/index'>;
}
declare module 'serverless/lib/plugins/aws/package/compile/functions/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/compile/functions/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/index'>;
}
declare module 'serverless/lib/plugins/aws/package/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/index.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/generateArtifactDirectoryName.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/generateCoreTemplate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/generateCoreTemplate'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/generateCoreTemplate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/generateCoreTemplate.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/mergeCustomProviderResources.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/mergeIamTemplates.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/mergeIamTemplates'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/mergeIamTemplates.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/mergeIamTemplates.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/saveCompiledTemplate.test'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/saveServiceState.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/saveServiceState'>;
}
declare module 'serverless/lib/plugins/aws/package/lib/saveServiceState.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/package/lib/saveServiceState.test'>;
}
declare module 'serverless/lib/plugins/aws/provider/awsProvider.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/provider/awsProvider'>;
}
declare module 'serverless/lib/plugins/aws/provider/awsProvider.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/provider/awsProvider.test'>;
}
declare module 'serverless/lib/plugins/aws/remove/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/index'>;
}
declare module 'serverless/lib/plugins/aws/remove/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/index.test'>;
}
declare module 'serverless/lib/plugins/aws/remove/lib/bucket.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/lib/bucket'>;
}
declare module 'serverless/lib/plugins/aws/remove/lib/bucket.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/lib/bucket.test'>;
}
declare module 'serverless/lib/plugins/aws/remove/lib/stack.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/lib/stack'>;
}
declare module 'serverless/lib/plugins/aws/remove/lib/stack.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/remove/lib/stack.test'>;
}
declare module 'serverless/lib/plugins/aws/rollback/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/rollback/index'>;
}
declare module 'serverless/lib/plugins/aws/rollback/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/rollback/index.test'>;
}
declare module 'serverless/lib/plugins/aws/utils/findAndGroupDeployments.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/findAndGroupDeployments'>;
}
declare module 'serverless/lib/plugins/aws/utils/findAndGroupDeployments.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/findAndGroupDeployments.test'>;
}
declare module 'serverless/lib/plugins/aws/utils/findReferences.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/findReferences'>;
}
declare module 'serverless/lib/plugins/aws/utils/findReferences.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/findReferences.test'>;
}
declare module 'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks'>;
}
declare module 'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/aws/utils/getS3ObjectsFromStacks.test'>;
}
declare module 'serverless/lib/plugins/config/config.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/config/config'>;
}
declare module 'serverless/lib/plugins/config/config.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/config/config.test'>;
}
declare module 'serverless/lib/plugins/create/create.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/create'>;
}
declare module 'serverless/lib/plugins/create/create.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/create.test'>;
}
declare module 'serverless/lib/plugins/create/templates/aws-nodejs/handler.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/aws-nodejs/handler'>;
}
declare module 'serverless/lib/plugins/create/templates/azure-nodejs/handler.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/azure-nodejs/handler'>;
}
declare module 'serverless/lib/plugins/create/templates/openwhisk-nodejs/handler.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/openwhisk-nodejs/handler'>;
}
declare module 'serverless/lib/plugins/create/templates/plugin/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/create/templates/plugin/index'>;
}
declare module 'serverless/lib/plugins/deploy/deploy.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/deploy/deploy'>;
}
declare module 'serverless/lib/plugins/deploy/deploy.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/deploy/deploy.test'>;
}
declare module 'serverless/lib/plugins/info/info.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/info/info'>;
}
declare module 'serverless/lib/plugins/info/info.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/info/info.test'>;
}
declare module 'serverless/lib/plugins/install/install.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/install/install'>;
}
declare module 'serverless/lib/plugins/install/install.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/install/install.test'>;
}
declare module 'serverless/lib/plugins/invoke/invoke.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/invoke/invoke'>;
}
declare module 'serverless/lib/plugins/invoke/invoke.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/invoke/invoke.test'>;
}
declare module 'serverless/lib/plugins/logs/logs.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/logs/logs'>;
}
declare module 'serverless/lib/plugins/logs/logs.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/logs/logs.test'>;
}
declare module 'serverless/lib/plugins/metrics/metrics.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/metrics/metrics'>;
}
declare module 'serverless/lib/plugins/metrics/metrics.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/metrics/metrics.test'>;
}
declare module 'serverless/lib/plugins/package/lib/packageService.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/lib/packageService'>;
}
declare module 'serverless/lib/plugins/package/lib/packageService.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/lib/packageService.test'>;
}
declare module 'serverless/lib/plugins/package/lib/zipService.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/lib/zipService'>;
}
declare module 'serverless/lib/plugins/package/lib/zipService.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/lib/zipService.test'>;
}
declare module 'serverless/lib/plugins/package/package.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/package'>;
}
declare module 'serverless/lib/plugins/package/package.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/package/package.test'>;
}
declare module 'serverless/lib/plugins/remove/remove.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/remove/remove'>;
}
declare module 'serverless/lib/plugins/remove/remove.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/remove/remove.test'>;
}
declare module 'serverless/lib/plugins/rollback/index.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/rollback/index'>;
}
declare module 'serverless/lib/plugins/rollback/index.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/rollback/index.test'>;
}
declare module 'serverless/lib/plugins/slstats/slstats.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/slstats/slstats'>;
}
declare module 'serverless/lib/plugins/slstats/slstats.test.js' {
  declare module.exports: $Exports<'serverless/lib/plugins/slstats/slstats.test'>;
}
declare module 'serverless/lib/Serverless.js' {
  declare module.exports: $Exports<'serverless/lib/Serverless'>;
}
declare module 'serverless/lib/Serverless.test.js' {
  declare module.exports: $Exports<'serverless/lib/Serverless.test'>;
}
declare module 'serverless/scripts/postinstall.js' {
  declare module.exports: $Exports<'serverless/scripts/postinstall'>;
}
declare module 'serverless/scripts/preuninstall.js' {
  declare module.exports: $Exports<'serverless/scripts/preuninstall'>;
}
