// flow-typed signature: d4621d14991cc7b62f78b321cb0e2fb5
// flow-typed version: <<STUB>>/@jongold/further_v^1.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jongold/further'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@jongold/further' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jongold/further/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jongold/further/lib/index.js' {
  declare module.exports: $Exports<'@jongold/further/lib/index'>;
}
